SELECT '112020' as MesAno
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END) Emprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 2 THEN 2 ELSE null END) ELSE NULL END) Solicitou
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 3 THEN 3 ELSE null END) ELSE NULL END) NaoEmprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN 1 END) Total
        ,(COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END) / COUNT(CASE WHEN B005 = 1 THEN 1 END)) *100 as PercentualEmprestimoParaSolicitantes
        ,COUNT(*) QtdTotalRespondentes
FROM `PNAD_COVID.PNAD_COVID_112020` 
UNION ALL
SELECT '102020' as MesAno
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END)  Emprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 2 THEN 2 ELSE null END) ELSE NULL END) Solicitou
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 3 THEN 3 ELSE null END) ELSE NULL END) NaoEmprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN 1 END) Total
        ,(COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END) / COUNT(CASE WHEN B005 = 1 THEN 1 END)) *100 as PercentualEmprestimoParaSolicitantes
        ,COUNT(*) QtdTotalRespondentes
FROM `PNAD_COVID.PNAD_COVID_102020` 
UNION ALL
SELECT '092020' as MesAno
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END)  Emprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 2 THEN 2 ELSE null END) ELSE NULL END) Solicitou
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 3 THEN 3 ELSE null END) ELSE NULL END) NaoEmprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN 1 END) Total
        ,(COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END) / COUNT(CASE WHEN B005 = 1 THEN 1 END)) *100 as PercentualEmprestimoParaSolicitantes
        ,COUNT(*) QtdTotalRespondentes
FROM `PNAD_COVID.PNAD_COVID_092020` 
UNION ALL
SELECT '082020' as MesAno
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END)  Emprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 2 THEN 2 ELSE null END) ELSE NULL END) Solicitou
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 3 THEN 3 ELSE null END) ELSE NULL END) NaoEmprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN 1 END) Total
        ,(COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END) / COUNT(CASE WHEN B005 = 1 THEN 1 END)) *100 as PercentualEmprestimoParaSolicitantes
        ,COUNT(*) QtdTotalRespondentes
FROM `PNAD_COVID.PNAD_COVID_082020`
UNION ALL
SELECT '072020' as MesAno
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END)  Emprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 2 THEN 2 ELSE null END) ELSE NULL END) Solicitou
        ,COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 3 THEN 3 ELSE null END) ELSE NULL END) NaoEmprestimo
        ,COUNT(CASE WHEN B005 = 1 THEN 1 END) Total
        ,(COUNT(CASE WHEN B005 = 1 THEN (CASE E001 WHEN 1 THEN 1 ELSE null END) ELSE NULL END) / COUNT(CASE WHEN B005 = 1 THEN 1 END)) *100 as PercentualEmprestimoParaSolicitantes
        ,COUNT(*) QtdTotalRespondentes
FROM `PNAD_COVID.PNAD_COVID_072020` 
 ORDER BY 1